using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a global preset category (e.g. PersonalInformation, MedicalInformation).
/// System-initialised and read-only — never modified at runtime.
/// Maps to the "categories" table in the database.
/// </summary>
[Table("categories")]
public class Category
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// The category name, e.g. "PersonalInformation". Must be unique.
    /// </summary>
    [Column("category")]
    public required string CategoryName { get; set; }

    // Navigation: all preset field definitions that belong to this category.
    public ICollection<Field> Fields { get; set; } = new List<Field>();
}
