using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a preset field definition shared across all workers
/// (e.g. "Full Name", "Blood Type", "Resume").
/// System-initialised and read-only — never modified at runtime.
/// Maps to the "fields" table in the database.
/// </summary>
[Table("fields")]
public class Field
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// System key name, e.g. "full_name". Unique within a category.
    /// </summary>
    [Column("field")]
    public required string FieldName { get; set; }

    /// <summary>
    /// Foreign key referencing the category this field belongs to.
    /// </summary>
    [Column("category_id")]
    public Guid CategoryId { get; set; }

    /// <summary>
    /// Human-readable display label shown in the UI, e.g. "Full Name".
    /// Unique within a category.
    /// </summary>
    [Column("label")]
    public required string Label { get; set; }

    /// <summary>
    /// The allowed data type for values stored against this field.
    /// Either "text" or "file". Enforced at the application layer.
    /// </summary>
    [Column("allowed_type")]
    public required string AllowedType { get; set; }

    // Navigation: the category this field belongs to.
    public Category Category { get; set; } = null!;

    // Navigation: all worker_info rows that reference this preset field.
    public ICollection<WorkerInfo> WorkerInfos { get; set; } = new List<WorkerInfo>();
}
