using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a system notification delivered to either a worker or an employer.
/// Exactly one of RecipientWorkerId / RecipientEmployerId must be non-null
/// (enforced by DB CHECK constraint in AppDbContext.OnModelCreating).
///
/// Supported notification types:
///   NEW_REQUEST       — sent to worker when an employer creates a request
///   REQUEST_REVIEWED  — sent to employer when a worker submits their review
///   ACCESS_REVOKED    — sent to employer when a worker revokes access
///
/// Maps to the "notification" table in the database.
/// </summary>
[Table("notification")]
public class Notification
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Timestamp of when the notification was created. Set by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// FK to the worker recipient. Non-null when the notification is for a worker.
    /// Mutually exclusive with RecipientEmployerId.
    /// </summary>
    [Column("recipient_worker_id")]
    public Guid? RecipientWorkerId { get; set; }

    /// <summary>
    /// FK to the employer recipient. Non-null when the notification is for an employer.
    /// Mutually exclusive with RecipientWorkerId.
    /// </summary>
    [Column("recipient_employer_id")]
    public Guid? RecipientEmployerId { get; set; }

    /// <summary>
    /// The notification type. One of:
    ///   "NEW_REQUEST" | "REQUEST_REVIEWED" | "ACCESS_REVOKED"
    /// </summary>
    [Column("type")]
    public required string Type { get; set; }

    /// <summary>
    /// FK to the request this notification relates to.
    /// </summary>
    [Column("request_id")]
    public Guid? RequestId { get; set; }

    /// <summary>
    /// Whether the recipient has read this notification.
    /// </summary>
    [Column("is_read")]
    public bool IsRead { get; set; } = false;

    // Navigation
    public Request? Request { get; set; }
}
