using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents an authorisation record for a single field within a data-access request.
/// Tracks the two-phase lifecycle:
///   Request phase  → field_id set, info_id null, status = Pending(0)
///   Approved phase → info_id filled in,           status = Approved(1)
///
/// DB CHECK constraints (enforced in AppDbContext.OnModelCreating):
///   • status IN (1, 3)  →  info_id must NOT be null
///   • field_id IS NOT NULL  OR  info_id IS NOT NULL  (at least one must be set)
///
/// Maps to the "permission" table in the database.
/// </summary>
[Table("permission")]
public class Permission
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the request this permission belongs to.
    /// </summary>
    [Column("request_id")]
    public Guid RequestId { get; set; }

    /// <summary>
    /// Foreign key referencing the worker whose data is being requested.
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// FK to the preset field definition being requested.
    /// Set when the employer selects a preset field.
    /// Null for custom (Other) fields created via custom_request.
    /// </summary>
    [Column("field_id")]
    public Guid? FieldId { get; set; }

    /// <summary>
    /// FK to the worker's actual data row (worker_info).
    /// Null in the request phase; filled in when the worker approves.
    /// For custom fields created via Add Item, set immediately on creation.
    /// </summary>
    [Column("info_id")]
    public Guid? InfoId { get; set; }

    /// <summary>
    /// Permission lifecycle status:
    ///   0 = Pending   — awaiting worker review
    ///   1 = Approved  — worker granted access (info_id must be set)
    ///   2 = Rejected  — worker denied; terminal state
    ///   3 = Revoked   — was approved, later revoked by worker; terminal state
    /// </summary>
    [Column("status")]
    public int Status { get; set; } = 0;

    /// <summary>
    /// Timestamp of the last status change.
    /// </summary>
    [Column("last_updated_at")]
    public DateTime? LastUpdatedAt { get; set; }

    // Navigation: the request this permission belongs to.
    public Request Request { get; set; } = null!;

    // Navigation: the preset field definition (null for custom fields).
    public Field? Field { get; set; }

    // Navigation: the worker_info row holding the actual value (null until approved).
    public WorkerInfo? WorkerInfo { get; set; }
}
