using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a single data item owned by a worker.
/// Covers both preset fields (field_id is set, custom_label is null)
/// and custom "Other" fields (field_id is null, custom_label is set).
/// Exactly one of field_id / custom_label must be non-null (enforced by DB CHECK).
/// Maps to the "worker_info" table in the database.
/// </summary>
[Table("worker_info")]
public class WorkerInfo
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the worker who owns this data item.
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// FK to the global preset field definition.
    /// Non-null for preset fields; null for custom fields.
    /// </summary>
    [Column("field_id")]
    public Guid? FieldId { get; set; }

    /// <summary>
    /// The label for a custom (Other) field created by the worker.
    /// Non-null for custom fields; null for preset fields.
    /// </summary>
    [Column("custom_label")]
    public string? CustomLabel { get; set; }

    /// <summary>
    /// Data type of the stored value: "text" or "file".
    /// Immutable after creation — changing type requires deleting and re-creating the row.
    /// </summary>
    [Column("type")]
    public required string Type { get; set; }

    /// <summary>
    /// The stored value.
    /// For type="text": the text content.
    /// For type="file": the Supabase storage path (used to generate a signed URL).
    /// Null means the worker has not filled in this field yet.
    /// </summary>
    [Column("value")]
    public string? Value { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Set by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Timestamp of the last update to this record.
    /// </summary>
    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    // Navigation: the preset field definition (null for custom fields).
    public Field? Field { get; set; }

    // Navigation: the worker who owns this item.
    public Worker Worker { get; set; } = null!;

    // Navigation: permission rows that point to this data item.
    public ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}
